allcripto/urls.py
from django.urls import path

from .views import BitcoinNews, BitcoinDetail, EthereumNews, EthereumDetail

app_name = 'allcripto'

urlpatterns = [
    path('bitcoin/', BitcoinNews.as_view() , name="bitcoin_news"),
    path('ethereum/', EthereumNews.as_view(), name="ethereum_news"),
    path('<slug:slug>/', BitcoinDetail.as_view(), name="bitcoin_detail"),
    path('<slug:slug>/', EthereumDetail.as_view(), name="ethereum_detail")
]

newscripto/urls.py
from django.contrib import admin
from .views import HomePage
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name="home"),
    path('allcripto/', include('allcripto.urls', namespace='allcripto'))
]

allcripto/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.utils import timezone

class Bitcoin(models.Model):
    title = models.TextField(unique=True)
    header = models.TextField(unique=True)
    paragraph = models.TextField(unique=True)
    slug = AutoSlugField(max_length=250, populate_from = 'title', null=True, unique=True)
    extracted_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title + ' ' + self.header + ' ' + self.paragraph

class Ethereum(models.Model):
    title = models.TextField(unique=True)
    header = models.TextField(unique=True)
    paragraph = models.TextField(unique=True)
    slug = AutoSlugField(max_length=250, populate_from = 'title', null=True, unique=True)
    extracted_at = models.DateTimeField(default=timezone.now)

class MetaVerse(models.Model):
    title = models.TextField(unique=True)
    header = models.TextField(unique=True)
    paragraph = models.TextField(unique=True)
    slug = AutoSlugField(max_length=250, populate_from = 'title', null=True, unique=True)
    extracted_at = models.DateTimeField(default=timezone.now)

class Tutorial(models.Model):
    title = models.TextField(unique=True)
    header = models.TextField(unique=True)
    paragraph = models.TextField(unique=True)
    slug = AutoSlugField(max_length=250, populate_from = 'title', null=True, unique=True)
    extracted_at = models.DateTimeField(default=timezone.now)

class Prices(models.Model):
    title = models.TextField(unique=True)
    header = models.TextField(unique=True)
    paragraph = models.TextField(unique=True)
    slug = AutoSlugField(max_length=250, populate_from = 'title', null=True, unique=True)
    extracted_at = models.DateTimeField(default=timezone.now)

class Business(models.Model):
    title = models.TextField(unique=True)
    header = models.TextField(unique=True)
    paragraph = models.TextField(unique=True)
    slug = AutoSlugField(max_length=250, populate_from = 'title', null=True, unique=True)
    extracted_at = models.DateTimeField(default=timezone.now)

allcripto/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from .models import Bitcoin, Ethereum, MetaVerse, Tutorial, Prices, Business

class BitcoinNews(TemplateView):
    template_name = 'allcripto/bitcoin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bitcoin_news'] = Bitcoin.objects.all()
        return context

class BitcoinDetail(DetailView):
    model = Bitcoin
    template_name = 'allcripto/bitcoin_detail.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news = Bitcoin.objects.filter(slug=self.kwargs.get('slug'))
        return context


class EthereumNews(TemplateView):
    template_name = 'allcripto/ethereum.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ethereum_news'] = Ethereum.objects.all()
        return context

class EthereumDetail(DetailView):
    model = Ethereum
    template_name = 'allcripto/ethereum_detail.html'
    context_object_name = 'news_eth'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news = Ethereum.objects.filter(slug=self.kwargs.get('slug'))
        return context

newscripto/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

templates/allcripto/bitcoin.html
{% block content %}
    
{% for bit in bitcoin_news %}
<a href=" {% url 'allcripto:bitcoin_detail' slug=bit.slug %} ">

<li>{{ bit.title }}</li>
</a>
<span>{{ bit.header }}</span>
{% endfor %}

{% endblock content %}

templates/allcripto/bitcoin_detail.html
{% block content %}
    
<h1>{{ news.title }}</h1>
<h3>{{ news.header }}</h3>
<p>{{ news.paragraph }}</p>
    
    
{% endblock content %}

templates/allcripto/ethereum.html
{% block content %}
    
{% for eth in ethereum_news %}
<a href=" {% url 'allcripto:ethereum_detail' slug=eth.slug %} ">

<li>{{ eth.title }}</li>
</a>
<span>{{ eth.header }}</span>


{% endfor %}
    
    
{% endblock content %}

templates/allcripto/ethereum_detail.html
{% block content %}
    
<h1>{{ news_eth.title }}</h1>
<h3>{{ news_eth.header }}</h3>
<p>{{ news_eth.paragraph }}</p>
    
    
{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <meta name="description" 
        content="Noticias cripto en un sola web" />
    <meta name="robots" content="index,follow">
    <title>All Crypto</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
    <body class="content">
    <section class="headers">
        <section class="title">
            <h3>Allcrypto</h3>
        </section>
        <section class="header-image">
            <img src="{% static 'images/allcripto.jpg' %}" alt="">
        </section>
    </section>
            {% block content %}
        <section class="category">
            <figure>
                <a href="allcripto/bitcoin">
                    <p>Bitcoin</p>
                <img class="items" src="{% static 'images/pexels-alesia-kozik-6765373.jpg' %}" alt="Bitcoin" ></a>
            </figure>
            <figure>
                <a href="allcripto/ethereum">
                    <img class="items" src="{% static 'images/pexels-jievani-8175569.jpg' %}" alt="Ethereum" >
                </a>
            </figure>
            <figure>
                <a href="#Metaverso">
                    <img class="items" src="{% static 'images/7 Altcoins Primed for a June Rally.png' %}" alt="Altcoins" ></a>
            </figure>
        </section>
        <section class="category">
            <figure>
                <a href="#Tutoriales"> 
                    <img class="items" src="{% static 'images/¿Cómo se crea una criptomoneda_ Solo necesitas 2 minutos y una app (1).png' %}" alt="Tutoriales" ></a>
            </figure>
            <figure>
                <a href="#Analisis de Precios">
                    <img class="items" src="{% static 'images/Mercado bursátil o forex gráfico en concepto gráfico _ Foto Premium.jpg'%}" alt="Analisis de Mercado" >
                </a>
            </figure>
            <figure>
                <a href="#Noticias de Negocios">
                    <img class="items" src="{% static 'images/job-gbf082170e_640.jpg'%}" alt="Noticias de Negocios" >
                </a>
            </figure>
        </section>
        {% endblock content %}
        <footer>
            <p>footer</p>
        </footer>
    </body>